package com.vk.education_bot.handler;

public enum UserState {
    MAIN_MENU,
    SECTION_SELECTION,
    PROJECT_SELECTION,
    ASKING_GENERAL_QUESTION,
    ASKING_PROJECT_QUESTION,
    ADMIN,
    ADMIN_ANSWER,
    ADMIN_DELETE_Q,
    ADMIN_DELETE_ADMIN,
    ADMIN_ADD_ADMIN,
    ADMIN_SECTION_SELECTION,
    ADMIN_SHOW_PROJECTS,
    ADMIN_NEW_PROJECT,
    ADMIN_EDIT_PROJECT,
    ADMIN_ACCEPT_EDITED_PROJECT,
    QUES_YES_NO,
    PROJ_YES_NO
}