spring:
  application:
    name: education-bot
  liquibase:
    change-log: classpath:/db/changelog/db.change-log-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/edu_bot
    username: postgres
    password: postgres

properties:
  vk:
    confirmationCode: ${CONFIRMATION_CODE}
    groupId: ${GROUP_ID}
    accessCode: ${ACCESS_CODE}
    supportUserId: ${SUPPORT_USER_ID}
  yandex-gpt:
    folderId: ${YC_FOLDER_ID}
    host: ${Y_GPT_HOST:https://llm.api.cloud.yandex.net}
